backend:
  name: test-repo
  # name: github
  # repo: wohfab/wohfab.github.io
  
media_folder: static/assets
public_folder: assets

collections:
  - name: pages
    label: Pages
    folder: content/pages
    create: true
    fields:
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: language, label: Language, widget: select, options: [de, en], default: [de]}
      - { name: bio, label: Display Bio?, widget: boolean, default: false } 
      - { name: body, label: Body, widget: markdown }
      

  - name: projects
    label: Projects
    folder: content/projects
    create: true
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: tags, label: Tags, widget: list, field: { name: tag, label: Tag } }
      - { name: language, label: Language, widget: select, options: [de, en], default: [en]}
      - { name: category, label: Category, widget: select, multiple: true, options: [code, photo, audio, video, design]}
      - { name: body, label: Body, widget: markdown }

  
  - name: resources
    label: Resources
    folder: content/resources
    create: true
    fields:
      - { name: title, label: Title }
      - { name: category, label: Category, widget: select, multiple: true, options: [category1, category2, category3]}
      - { name: tags, label: Tags, widget: list, field: { name: tag, label: Tag } }
      - { name: language, label: Language, widget: select, options: [de, en], default: [en]}
