backend:
  name: git-gateway

collections:
  - name: "settings"
    label: "Settings"
    files: ["_data/settings.json"]
    fields:
      - {
        name: "Site Name",
        label: "siteName",
        widget: "string"
      }
      -  {
        name: "Logo",
        label: "logo",
        widget: "image",
        required: false
      }
  - name: "writing"
    label: "Writing"
    folder: "writing"
    create: true
    slug: "{{ slug }}"
    fields:
      - {
        name: "title",
        label: "Title",
        widget: "string"
      }
      - {
        name: "date",
        label: "Publish Date",
        widget: "datetime"
      }
      -  {
        name: "body",
        label: "Body",
        widget: "markdown"
      }
      - {
        label: "Layout",
        name: "layout",
        widget: "hidden",
        default: "layout.njk"
      }

media_folder: "assets/img/"